// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3SKfbI5vhzZPbjYnGy_QZyhGg3voTens',
    appId: '1:182609886666:web:617f2c2dbe447770c52333',
    messagingSenderId: '182609886666',
    projectId: 'taf-003-firebase-auth',
    authDomain: 'taf-003-firebase-auth.firebaseapp.com',
    storageBucket: 'taf-003-firebase-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNGp0XMQQg6EY8sEsEEONTi30kZJJpS8',
    appId: '1:182609886666:android:2ec3a3af5949ae7ac52333',
    messagingSenderId: '182609886666',
    projectId: 'taf-003-firebase-auth',
    storageBucket: 'taf-003-firebase-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO-3DUM9eX8FyF1P9dLHNlJI4yp2Q99AU',
    appId: '1:182609886666:ios:060ffd7cc3c85adac52333',
    messagingSenderId: '182609886666',
    projectId: 'taf-003-firebase-auth',
    storageBucket: 'taf-003-firebase-auth.appspot.com',
    iosBundleId: 'com.example.fLesson18',
  );
}
